import './globals.css'
import { Fira_Sans } from 'next/font/google'

const inter_sans = Fira_Sans({ subsets: ['latin'], weight: ['400']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter_sans.className}>{children}</body>
    </html>
  )
}
